/**
 * Auto-generated stubs for undefined-call diagnostics in parson.
 *
 * Each name is exported as a no-op function returning a safe default.
 * The entry module injects a top-of-file import binding these names so
 * unresolved references at `function tableName(... fabs ...)` lexically
 * resolve. Generated by scripts/auto-stub-undefined-calls.ts (Meta-A,
 * scripted-only).
 *
 * BRIDGE: auto-stub-undefined-call — scripted bootstrap, replace with
 * a real implementation when the call site's behaviour matters.
 */

export function __acrt_iob_func(..._args: any[]): any { /* BRIDGE: auto-stub-undefined-call — __acrt_iob_func */ return 0; }
export function __strto_set_end(..._args: any[]): any { /* BRIDGE: auto-stub-undefined-call — __strto_set_end */ return 0; }
export function __struct_ptr_at(..._args: any[]): any { /* BRIDGE: auto-stub-undefined-call — __struct_ptr_at */ return 0; }
export function max(..._args: any[]): any { /* BRIDGE: auto-stub-undefined-call — max */ return 0; }
export function printf_format(..._args: any[]): any { /* BRIDGE: auto-stub-undefined-call — printf_format */ return 0; }
