/**
 * Auto-generated stubs for undefined-call diagnostics in rfc1321-md5.
 *
 * Each name is exported as a no-op function returning a safe default.
 * The entry module injects a top-of-file import binding these names so
 * unresolved references at `function tableName(... fabs ...)` lexically
 * resolve. Generated by scripts/auto-stub-undefined-calls.ts (Meta-A,
 * scripted-only).
 *
 * BRIDGE: auto-stub-undefined-call — scripted bootstrap, replace with
 * a real implementation when the call site's behaviour matters.
 */

export function fread(..._args: any[]): any { /* BRIDGE: auto-stub-undefined-call — fread */ return 0; }
