/**
 * Auto-generated stubs for undefined-call diagnostics in xxhash.
 *
 * Each name is exported as a no-op function returning a safe default.
 * The entry module injects a top-of-file import binding these names so
 * unresolved references at `function tableName(... fabs ...)` lexically
 * resolve. Generated by scripts/auto-stub-undefined-calls.ts (Meta-A,
 * scripted-only).
 *
 * BRIDGE: auto-stub-undefined-call — scripted bootstrap, replace with
 * a real implementation when the call site's behaviour matters.
 */

export function __builtin_llabs(..._args: any[]): any { /* BRIDGE: auto-stub-undefined-call — __builtin_llabs */ return 0; }
export function __struct_ptr_at(..._args: any[]): any { /* BRIDGE: auto-stub-undefined-call — __struct_ptr_at */ return 0; }
export function _mm_set_epi64x(..._args: any[]): any { /* BRIDGE: auto-stub-undefined-call — _mm_set_epi64x */ return 0; }
export function _mm_slli_epi64(..._args: any[]): any { /* BRIDGE: auto-stub-undefined-call — _mm_slli_epi64 */ return 0; }
export function _mm_srli_epi64(..._args: any[]): any { /* BRIDGE: auto-stub-undefined-call — _mm_srli_epi64 */ return 0; }
export function labs(..._args: any[]): any { /* BRIDGE: auto-stub-undefined-call — labs */ return 0; }
